name: build-windows

on:
  # push:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        default: true
        description: Use binary cache

jobs:
  build-maadeps-windows:
    strategy:
      matrix:
        os: [windows]
        arch: [x86, x64]
      fail-fast: false
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 720
    steps:
      - name: Windows runner hack
        shell: cmd
        run: |
          dir d:\a
          cd ..
          mkdir C:\MaaDeps
          rmdir MaaDeps
          mklink /j MaaDeps C:\MaaDeps
          dism /Online /Disable-Feature /FeatureName:Windows-Defender /Remove /NoRestart /Quiet
          cd .

      - name: Windows runner hack (2)
        uses: al-cheb/configure-pagefile-action@v1.3
        with:
          minimum-size: 16GB
          maximum-size: 16GB
          disk-root: "D:"

      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - uses: actions/cache@v3
        with:
          path: |
            vcpkg/downloads/
          key: cache-downloads-${{ matrix.os }}-${{ matrix.arch }}-${{ hashfiles('vcpkg-overlay', 'vcpkg*.json') }}

      - uses: ilammy/msvc-dev-cmd@v1
        id: msvc-env
        with:
          arch: amd64${{ matrix.arch != 'x64' && format('_{0}', matrix.arch) || '' }}

      - name: Setup MSVC environment
        run: |
          echo "CC=cl" >> $GITHUB_ENV
          echo "CXX=cl" >> $GITHUB_ENV

      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          windows_compile_environment: msvc

      - name: Set target
        run: |
          lower() { printf '%s\n' "${1,,}"; }
          export RUNNER_OS=$(lower ${{runner.os}})
          export OS=$(echo $RUNNER_OS | sed 's/macOS/osx/I')
          echo "TARGET=${{ matrix.arch }}-${OS}" >> $GITHUB_ENV

      - name: Build MaaDeps
        run: |
          # 显示环境信息
          echo "Current environment:"
          echo "TARGET: $TARGET"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          cl.exe /?
          
          # 显示 Python 版本和位置
          python3 --version
          which python3
          
          # 显示目录结构
          ls -la
          
          for attempt in 1 2 3
          do
            echo "Build attempt $attempt:"
            # 移除 --verbose 参数
            python3 build.py --tarball --target maa-$TARGET && break
            
            # 在失败时收集更多信息
            if [ $? -ne 0 ]; then
              echo "Build failed on attempt $attempt"
              
              # 如果 vcpkg/buildtrees 目录存在才执行
              if [ -d "vcpkg/buildtrees" ]; then
                echo "Showing build logs:"
                find vcpkg/buildtrees -name "*.log" -type f -exec cat {} \;
              fi
              
              # 显示 CMake 错误日志（如果存在）
              find . -name "CMakeError.log" -type f -exec cat {} \;
              
              # 显示磁盘空间信息
              echo "Disk space information:"
              df -h
              
              # 如果不是最后一次尝试，清理并重试
              if [ $attempt -lt 3 ]; then
                echo "Cleaning up for next attempt..."
                if [ -d "vcpkg/buildtrees" ]; then
                  rm -rf vcpkg/buildtrees/**/*.{o,obj,a,lib}
                fi
              fi
            fi
            
            [[ $attempt != 3 ]]  # fail on last attempt
          done

      - name: Collect Logs
        if: always()  # Ensure logs are collected even if build fails
        run: |
          mkdir -p logs
          # Only search for CMakeError.log files
          find . -name "CMakeError.log" -type f -exec cp {} logs/ \; || true
          # Only search buildtrees if the directory exists
          if [ -d "vcpkg/buildtrees" ]; then
            find vcpkg/buildtrees -name "*.log" -type f -exec cp {} logs/ \; || true
          fi
          # Create tar.gz even if no logs were found
          tar czf build-logs.tar.gz logs/

      - name: Upload Build Logs
        if: always()  # 确保即使构建失败也上传日志
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ env.TARGET }}
          path: build-logs.tar.gz

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tarball-${{ env.TARGET }}
          path: tarball

      - name: release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
        shell: bash
        run: |
          gh release create "$TAG_NAME" --prerelease || true  # accept existing release
          gh release upload "$TAG_NAME" tarball/*





