name: probe

on:
  workflow_dispatch:

jobs:
  probe:
    runs-on: windows-latest
    steps:
    - name: Set Symlink for Windows
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        cd
        dir /a c:\
        dir /a d:\
        wmic pagefile list /format:list
        tasklist
        dism /Online /Disable-Feature /FeatureName:Windows-Defender /Remove /NoRestart
        tasklist